Models/Tablero.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using tl2_proyecto_TomasDLV.ViewModels;
namespace tl2_proyecto_TomasDLV.Models
{
    public class Tablero
    {
        private int id;
        private int idUsuarioPropietario;
        private string nombre;
        private string descripcion;

        public int Id { get => id; set => id = value; }
        public int IdUsuarioPropietario { get => idUsuarioPropietario; set => idUsuarioPropietario = value; }

        public string Descripcion { get => descripcion; set => descripcion = value; }
        public string Nombre { get => nombre; set => nombre = value; }
        public Tablero()
        {

        }
        public Tablero(CrearTableroViewModel tablero)
        {
            this.IdUsuarioPropietario = tablero.IdUsuarioPropietario;
            this.Nombre = tablero.Nombre;
            this.Descripcion = tablero.Descripcion;
        }
        public Tablero(ModificarTableroViewModel tablero)
        {
            this.Id = tablero.Id;
            this.IdUsuarioPropietario = tablero.IdUsuarioPropietario;
            this.Nombre = tablero.Nombre;
            this.Descripcion = tablero.Descripcion;
        }
    }
}

Controllers/TableroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using tl2_proyecto_TomasDLV.Models;
using tl2_proyecto_TomasDLV.Repositorios;
using tl2_proyecto_TomasDLV.ViewModels;

namespace tl2_proyecto_TomasDLV.Controllers
{
    public class TableroController : Controller
    {
        private readonly ILogger<TableroController> _logger;
        private readonly ITableroRepository _tableroRepository;
        private readonly ITareaRepository _tareaRepository;
        private readonly IUsuarioRepository _usuarioRepository;


        public TableroController(ILogger<TableroController> logger, ITableroRepository tableroRepository,ITareaRepository tareaRepository,IUsuarioRepository usuarioRepository)
        {
            _logger = logger;
            _tableroRepository = tableroRepository;
            _tareaRepository = tareaRepository;
            _usuarioRepository = usuarioRepository;
        }
        public IActionResult Index()
        {
            try
            {
                if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });

                var OwnBoards = new List<Tablero>();
                var BoardsWithTask = new List<Tablero>();
                var Users = _usuarioRepository.GetAllUser();
                
                
                if (esAdmin())
                {
                    OwnBoards = _tableroRepository.GetAllBoard();
                }
                else
                {
                    OwnBoards = _tableroRepository.GetAllBoardsByIdUser((int)HttpContext.Session.GetInt32("id"));
                    BoardsWithTask = _tableroRepository.GetAllBoardsHaveTask((int)HttpContext.Session.GetInt32("id"));
                }


                return View(new ListarTablerosViewModel(OwnBoards,BoardsWithTask,Users));
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
        [HttpGet]

        public IActionResult createBoard()
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });

            return View(new CrearTableroViewModel { IdUsuarioPropietario = (int)HttpContext.Session.GetInt32("id") });
        }

        [HttpPost]
        public IActionResult createBoard(CrearTableroViewModel board)
        {
            try
            {
                if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
                if (!ModelState.IsValid) return RedirectToAction("Index");
                _tableroRepository.CreateBoard(new Tablero(board));
                return RedirectToAction("Index");
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        public IActionResult editBoard(int idBoard)
        {
            
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            var board = _tableroRepository.GetByIdBoard(idBoard);
            var users = _usuarioRepository.GetAllUser();
            return View(new ModificarTableroViewModel(board,users));

        }

        [HttpPost]
        public IActionResult editBoard(ModificarTableroViewModel tablero)
        {
            try
            {
                if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
                if (!ModelState.IsValid) return RedirectToAction("Index");
                //Checkeo que el tablero sea de quien inicio la sesion o que sea un admin
                if (esAdmin() || (tablero.IdUsuarioPropietario == (int)HttpContext.Session.GetInt32("id")))
                {
                    _tableroRepository.UpdateBoard(tablero.Id, new Tablero(tablero));

                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public IActionResult removeBoard(int id)
        {
            try
            {
                if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });

                if (esAdmin())
                {
                    _tableroRepository.RemoveBoard(id);

                    return RedirectToAction("Index");
                }
                else
                {
                    if (_tableroRepository.GetByIdBoard(id).IdUsuarioPropietario == (int)HttpContext.Session.GetInt32("id"))
                    {
                        var tablero = _tableroRepository.GetByIdBoard(id);
                        tablero.IdUsuarioPropietario = -1;
                        _tableroRepository.UpdateBoard(id,tablero);
                        return RedirectToAction("Index");
                    }
                    return RedirectToRoute(new { controller = "Login", action = "Index" });
                }
            }
            catch (System.Exception ex)
            {
                _logger.LogError(ex.ToString());
                return RedirectToAction("Error");
            }

        }

        private bool logueado()
        {
            return HttpContext.Session.Keys.Any();
        }

        private bool esAdmin()
        {
            return HttpContext.Session.Keys.Any() && ((int)HttpContext.Session.GetInt32("rol") == 1);
        }
    }
}

Views/Tablero/createBoard.cshtml
@model tl2_proyecto_TomasDLV.ViewModels.CrearTableroViewModel
@{ 
    ViewData["Title"] = "Crear Tablero";
}



<h1>@ViewData["Title"]</h1>
<form asp-controller="Tablero" asp-action="createBoard" method="post">
    <input hidden asp-for="@Model.IdUsuarioPropietario" class="form-control" id="nombre" />
    
    <div class="form-group">
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" class="form-control" id="nombre" />
        <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Descripcion"></label>
        <input asp-for="@Model.Descripcion" class="form-control" id="nombre" />
    </div>
    <button type="submit" class="btn btn-primary" >Enviar</button>
</form>
@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Tablero/editBoard.cshtml
@model tl2_proyecto_TomasDLV.ViewModels.ModificarTableroViewModel
@{
    var userCheck = Context.Items["UserCheck"] as UserCheck;
}
@using tl2_proyecto_TomasDLV.Repositorios;
<form asp-controller="Tablero" asp-action="editBoard" method="post">
    <input type="hidden" asp-for="@Model.Id" />

    @if (userCheck.IsAdmin())
    {
        <div class="mb-3">
            <div class="form-group">
                <label class="form-label" asp-for="@Model.IdUsuarioPropietario">Propietario de Tablero: </label>
                <select asp-for="@Model.IdUsuarioPropietario" class="form-control" id="idUsuarioAsignado">
                    @if(Model.IdUsuarioPropietario == -1){
                        <option value="-1" selected>Sin Propietario</option>
                    }else{
                        <option value="">Sin Propietario</option>
                    }
                    
            @foreach (var user in Model.Usuarios)
            {
                if (user.Id == Model.IdUsuarioPropietario)
                {
                    <option value="@user.Id" selected>@user.Nombre_de_usuario</option>
                }
                else
                {
                    <option value="@user.Id">@user.Nombre_de_usuario</option>
                }
            }
                </select>
                <span asp-validation-for="@Model.IdUsuarioPropietario" class="text-danger"></span>
            </div>
        </div>
    }
    else
    {
        <input type="hidden" asp-for="@Model.IdUsuarioPropietario" />
    }
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Nombre">Nombre de Tablero: </label>
        <input asp-for="@Model.Nombre" class="form-control" />
        <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="@Model.Descripcion">Descripción: </label>
        <input asp-for="@Model.Descripcion" class="form-control" />
    </div>



    <button class="btn btn-primary" type="submit">Guardar Cambios</button>

</form>
<form asp-controller="Tablero" asp-action="removeBoard" method="post"
    onsubmit="return confirm('¿Estás seguro que quieres eliminar el tablero?')">
    <input type="hidden" name="id" value="@Model.Id" />
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tablero/index.cshtml
@model tl2_proyecto_TomasDLV.ViewModels.ListarTablerosViewModel;
@{
    ViewData["Title"] = "Index";
    var userCheck = Context.Items["UserCheck"] as UserCheck;

}
@using tl2_proyecto_TomasDLV.Repositorios;

<h3>Tableros</h3>

<div class="row mb-4">
    <div class="col-md-4 offset-md-4">
        <a asp-controller="Tablero" asp-action="createBoard" class="text-decoration-none">
            <div class="card bg-light text-center">
                <div class="card-body">
                    <h5 class="card-title">Crear un Nuevo Tablero</h5>
                </div>
            </div>
        </a>
    </div>
</div>
@if (userCheck.IsAdmin())
{
    <h5>Todos los Tableros</h5>
    <hr>
    <div class="row justify-content-center">
        @foreach (var t in Model.TablerosPropios)
        {
            var UserOwner = Model.Usuarios.FirstOrDefault(u => u.Id == t.IdUsuarioPropietario);
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@t.Nombre</h5>
                        <p class="card-text">Propietario: @(UserOwner != null ? UserOwner.Nombre_de_usuario : "Sin Propietario")</p>
                        <div class="btn-group-vertical d-flex justify-content-center" role="group">
                            <a asp-controller="Tarea" asp-action="Index" asp-route-idBoard="@t.Id"
                                class="btn btn-ver mb-2">Ver</a>
                            <a asp-controller="Tablero" asp-action="editBoard" asp-route-idBoard="@t.Id"
                                class="btn btn-editar">Editar</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <h5>Tus Tableros</h5>
    <hr>
    <div class="row justify-content-center">
        @foreach (var t in Model.TablerosPropios)
        {
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@t.Nombre</h5>
                        
                        <div class="btn-group-vertical d-flex justify-content-center" role="group">
                            <a asp-controller="Tarea" asp-action="Index" asp-route-idBoard="@t.Id"
                                class="btn btn-ver mb-2">Ver</a>
                            <a asp-controller="Tablero" asp-action="editBoard" asp-route-idBoard="@t.Id"
                                class="btn btn-editar">Editar</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <h5>Tableros Ajenos</h5>
    <hr>
    <div class="row justify-content-center">
        @foreach (var t in Model.TablerosAjenos)
        {
            var UserOwner = Model.Usuarios.FirstOrDefault(u => u.Id == t.IdUsuarioPropietario);
            <div class="col-md-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@t.Nombre</h5>
                        <p class="card-text">Propietario: @(UserOwner != null ? UserOwner.Nombre_de_usuario : "Sin Propietario")</p>
                        <div class="btn-group-vertical d-flex justify-content-center" role="group">
                            <a asp-controller="Tarea" asp-action="Index" asp-route-idBoard="@t.Id"
                                class="btn btn-ver mb-2">Ver</a>

                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}